version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: residencia
      POSTGRES_PASSWORD: residencia123
      POSTGRES_DB: residencia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://residencia:residencia123@db:5432/residencia
      JWT_SECRET: sua_chave_secreta
      FRONTEND_URL: http://localhost:3000
      PORT: 3001
      NODE_ENV: development
    ports:
      - "3001:3001"
    command: sh -c "npx prisma generate && npm run server:dev"
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

volumes:
  pgdata: 